using Content.Shared._NC.CharacterNotes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._NC.CharacterNotes;

[GenerateTypedNameReferences]
public sealed partial class NCCharacterNotesWindow : DefaultWindow
{
    public event Action<NetEntity, string, NCCharacterNoteColorTag, string>? OnSave;

    private const int MaxCustomNameLength = 32;

    private NetEntity _target;

    public NCCharacterNotesWindow()
    {
        RobustXamlLoader.Load(this);

        ColorTagOption.AddItem("Нейтральная", (int) NCCharacterNoteColorTag.Neutral);
        ColorTagOption.AddItem("Зеленая", (int) NCCharacterNoteColorTag.Green);
        ColorTagOption.AddItem("Желтая", (int) NCCharacterNoteColorTag.Yellow);
        ColorTagOption.AddItem("Красная", (int) NCCharacterNoteColorTag.Red);
        ColorTagOption.SelectId((int) NCCharacterNoteColorTag.Neutral);
        ColorTagOption.OnItemSelected += args => ColorTagOption.SelectId(args.Id);

        CustomNameInput.OnTextChanged += _ =>
        {
            if (CustomNameInput.Text.Length > MaxCustomNameLength)
                CustomNameInput.Text = CustomNameInput.Text[..MaxCustomNameLength];
        };

        SaveButton.OnPressed += _ =>
        {
            var colorTag = ColorTagOption.SelectedId switch
            {
                (int) NCCharacterNoteColorTag.Green => NCCharacterNoteColorTag.Green,
                (int) NCCharacterNoteColorTag.Yellow => NCCharacterNoteColorTag.Yellow,
                (int) NCCharacterNoteColorTag.Red => NCCharacterNoteColorTag.Red,
                _ => NCCharacterNoteColorTag.Neutral
            };

            OnSave?.Invoke(
                _target,
                CustomNameInput.Text,
                colorTag,
                Rope.Collapse(DescriptionInput.TextRope));
        };
    }

    public void UpdateState(NCCharacterNoteBoundUserInterfaceState state)
    {
        _target = state.Target;
        TargetNameLabel.Text = state.TargetName;
        CustomNameInput.Text = state.CustomName;
        ColorTagOption.SelectId((int) state.ColorTag);
        DescriptionInput.TextRope = new Rope.Leaf(state.Description);
    }
}
