# Medium Pistol — 9×19 CL
# Heavy Pistol — 11×20 CL
# Very Heavy Pistol — 13×23 CL
# SMG — 9×19 CL
# Heavy SMG — 11×20 CL
# Shotgun — 12g CL
# Assault Rifle — 5.56×45 CL
# Battle Rifle — 7.62×51 CL
# Sniper Rifle — 12.7×99 CL
# Grenade Launcher — 40×46 CL
# Rocket Launcher — 80mm CL