using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Vehicle;
using Content.Shared._NC.Vehicle.Components;
using Content.Shared._NC.Vehicle.Grid.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._NC.Vehicle.Ui;

[GenerateTypedNameReferences]
public sealed partial class RMCHardpointMenu : FancyWindow
{
    public event Action<string>? OnRemove;
    private readonly IEntityManager _entManager = IoCManager.Resolve<IEntityManager>();
    private RMCHardpointBoundUserInterface? _bui;
    
    public EntityUid? VehicleEntity;
    private bool _vehicleIconSet;
    private float _vehicleSpin;
    private const float VehicleSpinSpeed = MathHelper.TwoPi / 6f;
    private const float PixelsPerMeter = 32f;

    public RMCHardpointMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public RMCHardpointMenu(RMCHardpointBoundUserInterface bui) : this()
    {
        _bui = bui;
        VehicleEntity = bui.Owner;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        TrySetVehicleIcon();
        SpinVehicleIcon(args.DeltaSeconds);
    }

    private void SpinVehicleIcon(float frameTime)
    {
        if (!_vehicleIconSet || VehicleEntity == null || !_entManager.EntityExists(VehicleEntity.Value))
            return;

        _vehicleSpin += frameTime * VehicleSpinSpeed;

        if (_vehicleSpin > MathHelper.TwoPi)
            _vehicleSpin -= MathHelper.TwoPi;

        var dir = new Angle(_vehicleSpin).GetDir();
        VehicleIcon.OverrideDirection = dir;
    }

    private void TrySetVehicleIcon()
    {
        if (_vehicleIconSet)
            return;

        if (VehicleEntity is not { } vehicle || !_entManager.EntityExists(vehicle))
            return;

        VehicleIcon.SetEntity(vehicle);
        VehicleIcon.OverrideDirection = Direction.South;
        _vehicleSpin = 0f;
        _vehicleIconSet = true;
    }

    public void UpdateState(RMCHardpointBoundUserInterfaceState state)
    {
        TrySetVehicleIcon();

        var hasError = !string.IsNullOrWhiteSpace(state.Error);
        ErrorLabel.Visible = hasError;
        ErrorLabel.Text = hasError ? state.Error! : string.Empty;

        HardpointList.DisposeAllChildren();

        if (state.HasFrameIntegrity && state.FrameMaxIntegrity > 0f)
        {
            var percent = Math.Clamp(state.FrameIntegrity / state.FrameMaxIntegrity, 0f, 1f);
            FrameHealthRow.Visible = true;
            FrameHealthBar.Value = percent;
            FrameHealthBar.ForegroundStyleBoxOverride = CreateIntegrityStyle(percent);
            FrameHealthBar.BackgroundStyleBoxOverride = CreateIntegrityTrackStyle();
            FrameHealthLabel.Text = $"{MathF.Round(state.FrameIntegrity)}/{MathF.Round(state.FrameMaxIntegrity)} ({MathF.Round(percent * 100f)}%)";
        }
        else
        {
            FrameHealthRow.Visible = false;
        }

        foreach (var hardpoint in state.Hardpoints)
        {
            var isRemoving = hardpoint.Removing;
            var canRemove = hardpoint.HasItem && !isRemoving;
            var slotId = hardpoint.SlotId;

            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                MinSize = new Vector2(0, 48),
                MouseFilter = Control.MouseFilterMode.Stop
            };

            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = isRemoving
                    ? Color.FromHex("#2A1E10")
                    : hardpoint.HasItem
                        ? Color.FromHex("#0E1B2B")
                        : Color.FromHex("#121722"),
                BorderColor = isRemoving
                    ? Color.FromHex("#E2B36A")
                    : canRemove
                        ? Color.FromHex("#2D5E8E")
                        : Color.FromHex("#314155"),
                BorderThickness = new Thickness(1.5f)
            };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                Margin = new Thickness(6),
                HorizontalExpand = true
            };

            panel.AddChild(root);

            var spriteView = new SpriteView
            {
                Stretch = SpriteView.StretchMode.Fill,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(40, 40),
                OverrideDirection = Direction.South
            };

            if (hardpoint.InstalledEntity.HasValue &&
                _entManager.TryGetEntity(hardpoint.InstalledEntity.Value, out var installed) &&
                _entManager.EntityExists(installed))
            {
                spriteView.SetEntity(installed);
            }

            root.AddChild(spriteView);

            var centerColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 1,
                HorizontalExpand = true
            };

            var nameText = hardpoint.HasItem
                ? hardpoint.InstalledName ?? hardpoint.SlotId
                : Loc.GetString("rmc-hardpoint-ui-empty-slot");

            centerColumn.AddChild(new Label
            {
                Text = nameText,
                FontColorOverride = Color.FromHex("#E1EEFF")
            });

            centerColumn.AddChild(new Label
            {
                Text = $"{hardpoint.SlotId} ({hardpoint.HardpointType})",
                FontColorOverride = Color.FromHex("#8FA7C2")
            });

            var rightColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 3,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(170, 0)
            };

            if (isRemoving)
            {
                rightColumn.AddChild(new Label
                {
                    Text = Loc.GetString("rmc-hardpoint-ui-removing"),
                    FontColorOverride = Color.FromHex("#E2B36A")
                });
            }

            if (hardpoint.HasIntegrity)
            {
                var percent = hardpoint.MaxIntegrity > 0f
                    ? Math.Clamp(hardpoint.Integrity / hardpoint.MaxIntegrity, 0f, 1f)
                    : 0f;

                var barRow = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 8,
                    HorizontalExpand = true
                };

                var bar = new ProgressBar
                {
                    MinValue = 0,
                    MaxValue = 1,
                    Value = percent,
                    HorizontalExpand = true,
                    MinSize = new Vector2(120, 12)
                };

                bar.ForegroundStyleBoxOverride = CreateIntegrityStyle(percent);
                bar.BackgroundStyleBoxOverride = CreateIntegrityTrackStyle();

                var percentLabel = new Label
                {
                    Text = $"{MathF.Round(hardpoint.Integrity)}/{MathF.Round(hardpoint.MaxIntegrity)}",
                    VerticalAlignment = Control.VAlignment.Center,
                    FontColorOverride = Color.FromHex("#6BC7FF")
                };

                barRow.AddChild(bar);
                barRow.AddChild(percentLabel);

                rightColumn.AddChild(barRow);
            }

            if (canRemove)
            {
                var removeButton = new Button
                {
                    Text = Loc.GetString("rmc-hardpoint-ui-remove"),
                    MinSize = new Vector2(60, 24)
                };
                removeButton.OnPressed += _ => _bui?.RemoveHardpoint(slotId);
                rightColumn.AddChild(removeButton);
            }

            root.AddChild(centerColumn);
            root.AddChild(rightColumn);

            HardpointList.AddChild(panel);
        }
    }

    private static StyleBoxFlat CreateIntegrityTrackStyle()
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1E2B3B"),
            BorderColor = Color.FromHex("#3A4B5E"),
            BorderThickness = new Thickness(1f)
        };
    }

    private static StyleBoxFlat CreateIntegrityStyle(float percent)
    {
        var color = percent > 0.5f
            ? Color.FromHex("#53D188")
            : percent > 0.25f
                ? Color.FromHex("#D6C45A")
                : Color.FromHex("#E1786A");

        return new StyleBoxFlat
        {
            BackgroundColor = color
        };
    }
}
