using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Vehicle;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._NC.Vehicle.Ui;

[GenerateTypedNameReferences]
public sealed partial class RMCVehicleAmmoLoaderMenu : FancyWindow
{
    public event Action<string>? OnLoad;
    private readonly IEntityManager _entManager = IoCManager.Resolve<IEntityManager>();
    public EntityUid? LoaderEntity;
    private bool _iconSet;

    public RMCVehicleAmmoLoaderMenu()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_iconSet && LoaderEntity is { } loader && _entManager.EntityExists(loader))
        {
            LoaderIcon.SetEntity(loader);
            _iconSet = true;
        }
    }

    public void Update(IReadOnlyList<RMCVehicleAmmoLoaderUiEntry> hardpoints, int ammoAmount, int ammoMax)
    {
        AmmoCountLabel.Text = Loc.GetString("rmc-vehicle-ammo-loader-ui-ammo", ("current", ammoAmount), ("max", ammoMax));
        HardpointList.DisposeAllChildren();

        foreach (var hardpoint in hardpoints)
        {
            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                MinSize = new Vector2(0, 60),
                MouseFilter = Control.MouseFilterMode.Stop
            };

            panel.PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#0E1B2B"),
                    BorderColor = Color.FromHex("#2D5E8E"),
                    BorderThickness = new Thickness(1f)
                };

            var root = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 10,
                Margin = new Thickness(8),
                HorizontalExpand = true
            };

            panel.AddChild(root);

            var spriteView = new SpriteView
            {
                Stretch = SpriteView.StretchMode.Fill,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(44, 44),
                OverrideDirection = Direction.South
            };

            if (hardpoint.InstalledEntity.HasValue)
            {
                var installed = _entManager.GetEntity(hardpoint.InstalledEntity.Value);
                if (_entManager.EntityExists(installed))
                    spriteView.SetEntity(installed);
            }

            root.AddChild(spriteView);

            var infoColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 1,
                HorizontalExpand = true
            };

            infoColumn.AddChild(new Label
            {
                Text = hardpoint.InstalledName ?? hardpoint.SlotId,
                FontColorOverride = Color.FromHex("#E1EEFF")
            });

            infoColumn.AddChild(new Label
            {
                Text = Loc.GetString("rmc-vehicle-ammo-loader-ui-slot", ("slot", hardpoint.SlotId), ("type", hardpoint.HardpointType)),
                FontColorOverride = Color.FromHex("#8FA7C2")
            });

            var ammoColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 2,
                MinSize = new Vector2(160, 0),
                VerticalAlignment = Control.VAlignment.Center
            };

            ammoColumn.AddChild(new Label
            {
                Text = Loc.GetString("rmc-vehicle-ammo-loader-ui-chambered", ("current", hardpoint.ChamberedRounds), ("max", hardpoint.MagazineSize)),
                FontColorOverride = Color.FromHex("#6BC7FF")
            });

            ammoColumn.AddChild(new Label
            {
                Text = Loc.GetString("rmc-vehicle-ammo-loader-ui-stored", ("current", hardpoint.StoredMagazines), ("max", hardpoint.MaxStoredMagazines)),
                FontColorOverride = Color.FromHex("#6BC7FF")
            });

            var buttonColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                VerticalAlignment = Control.VAlignment.Center,
                MinSize = new Vector2(80, 0)
            };

            var loadButton = new Button
            {
                Text = hardpoint.CanLoad ? Loc.GetString("rmc-vehicle-ammo-loader-ui-load") : Loc.GetString("rmc-vehicle-ammo-loader-ui-full"),
                Disabled = !hardpoint.CanLoad || ammoAmount <= 0,
                MinSize = new Vector2(80, 26)
            };

            var slotId = hardpoint.SlotId;
            loadButton.OnPressed += _ => OnLoad?.Invoke(slotId);

            buttonColumn.AddChild(loadButton);

            root.AddChild(infoColumn);
            root.AddChild(ammoColumn);
            root.AddChild(buttonColumn);

            HardpointList.AddChild(panel);
        }
    }
}
