- type: job
  id: BiotechnicaBotanist
  name: Ботаник Biotechnica
  description: 'Научный персонал. Растит и перегоняет овощи в пищу, выводит новые сорта растений.'
  playTimeTracker: JobBiotechnicaBotanist
  weight: 10
  salary: 150
  icon: "JobIconBiotechAgrarian"
  startingGear: BiotechnicaBotanistGear
  access:
    - Biotech_Botany
    - Biotech_Staff
    - Biotech_Lab
    - Biotech_General
    - NC_General

- type: startingGear
  id: BiotechnicaBotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotechnica
    back: ClothingBackpackBiotechnica
    shoes: ClothingShoesColorWhite
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesNitrile
    id: BiotechnicaBotanistPDA
    belt: ClothingBeltBiotechnicaBotanyFilled
    outerClothing: ClothingOuterApronBiotechnicaBotany
