- type: job
  id: BiotechnicaBotanist
  name: Ботаник Biotechnica
  description: 'Научный персонал, растит и перегоняет овощи в пищу, выводит новые сорта растений'
  playTimeTracker: JobBiotechnicaBotanist
  weight: 10
  salary: 150
  icon: "JobIconBiotechAgrarian"
  startingGear: BiotechnicaBotanistGear
  access:
    - Biotech_Staff
    - Biotech_Lab
    - Biotech_General

- type: startingGear
  id: BiotechnicaBotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotech
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: TraumaTeamChiefPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
