- type: job
  id: BiotechnicaChief
  name: Руководитель объекта Biotechnica
  description: 'Руководитель отдела Biotechnica отвечает за управление и координацию всех операций, связанных с биотехнологическими исследованиями и разработками. Он обеспечивает эффективное использование ресурсов, поддерживает высокие стандарты безопасности и качества, а также способствует инновациям в области биотехнологий.'
  playTimeTracker: JobBiotechnicaChief
  weight: 100
  salary: 600
  icon: "JobIconBiotechChief"
  startingGear: BiotechnicaChiefGear
  access:
    - NC_General
    - Biotech_Director
    - Biotech_HeadOfDepartment
    - Biotech_MedTech
    - Biotech_Operative
    - Biotech_Staff
    - Biotech_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: TraumaSubscriber
      tier: Platinum

- type: startingGear
  id: BiotechnicaChiefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitArmoredBusinessSuit
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesSunglasses
    id: TraumaTeamChiefPDA
