- type: job
  id: BiotechnicaMedTech
  name: МедТех Biotechnica
  description: 'Научный персонал, Выполняет Медицинские операции, варит химикаты и производит медикаменты '
  playTimeTracker: JobBiotechnicaMedTech
  weight: 55
  salary: 200
  icon: "JobIconBiotechMedTech"
  startingGear: BiotechnicaMedTechGear
  access:
    - Biotech_MedTech
    - Biotech_Staff
    - Biotech_Lab
    - Biotech_General
    - NC_General

- type: startingGear
  id: BiotechnicaMedTechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotechnica
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: BiotechnicaMedTechPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
