- type: job
  id: BiotechnicaMedTech
  name: МедТех Biotechnica
  description: 'Научный персонал, Выполняет Медицинские операции, варит химикаты и производит медикаменты '
  playTimeTracker: JobBiotechnicaMedTech
  weight: 55
  salary: 200
  icon: "JobIconBiotechMedTech"
  startingGear: BiotechnicaMedTechGear
  access:
    - NC_General
    - Biotech_MedTech
    - Biotech_Staff
    - Biotech_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: TraumaSubscriber
      tier: Silver

- type: startingGear
  id: BiotechnicaMedTechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotech
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: TraumaTeamChiefPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
