- type: job
  id: BiotechnicaNetrunner
  name: Нетраннер Biotechnica
  description: 'Относится к рядовому составу, в иерархии стоит на ровне с Оперативниками. Может быть как пауком так и оказывать поддержку Оперативникам.'
  playTimeTracker: JobBiotechnicaNetrunner
  weight: 60
  salary: 400
  icon: "JobIconBiotechNetrunner"
  startingGear: BiotechnicaNetrunnerGear
  access:
    - Biotech_Operative
    - Biotech_Staff
    - Biotech_Security
    - Biotech_General
    - NC_General

- type: startingGear
  id: BiotechnicaNetrunnerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotech
    back: ClothingBackpackCyberdeckFilled
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: TraumaTeamChiefPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
