- type: job
  id: BiotechnicaOperativeLead
  name: Младший офицер Biotechnica
  description: 'Относится к Офицерскому составу, в иерархии стоит ниже Старшего Офицера но выше всего остального СБ.'
  playTimeTracker: JobBiotechnicaOperativeLead
  weight: 80
  salary: 350
  icon: "JobIconBiotechOfficer"
  startingGear: BiotechnicaOperativeLeadGear
  access:
    - NC_General
    - Biotech_Director
    - Biotech_HeadOfDepartment
    - Biotech_MedTech
    - Biotech_Operative
    - Biotech_Staff
    - Biotech_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: TraumaSubscriber
      tier: Silver

- type: startingGear
  id: BiotechnicaOperativeLeadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotech
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: TraumaTeamChiefPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
