- type: job
  id: BiotechnicaOperative
  name: Оперативник Biotechnica
  description: 'Относится к рядовому составу. Стоит выше обычного патрульного в иерархии.'
  playTimeTracker: JobBiotechnicaOperative
  weight: 70
  salary: 250
  icon: "JobIconBiotechOfficer"
  startingGear: BiotechnicaOperativeGear
  access:
    - Biotech_Operative
    - Biotech_Staff
    - Biotech_Security
    - Biotech_General
    - NC_General

- type: startingGear
  id: BiotechnicaOperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotechnica
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: BiotechnicaOperativePDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
