- type: job
  id: BiotechnicaParamedic
  name: Парамедик Biotechnica
  description: 'Относится к рядовому составу, стоит на ровне с Оперативниками в иерархии.'
  playTimeTracker: JobBiotechnicaParamedic
  weight: 60
  salary: 150
  icon: "JobIconBiotechParamed"
  startingGear: BiotechnicaParamedicGear
  access:
    - Biotech_MedTech
    - Biotech_Operative
    - Biotech_Staff
    - Biotech_General
    - NC_General

- type: startingGear
  id: BiotechnicaParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotechnica
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: BiotechnicaParamedicPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
