- type: job
  id: BiotechnicaTech
  name: Техник Biotechnica
  description: 'Научный персонал. Производит снаряжение и импланты, занимается тех обслуживанием объекта.'
  playTimeTracker: JobBiotechnicaTech
  weight: 50
  salary: 200
  icon: "JobIconBiotechTechnician"
  startingGear: BiotechnicaTechGear
  access:
    - Biotech_Staff
    - Biotech_Lab
    - Biotech_General
    - NC_General

- type: startingGear
  id: BiotechnicaTechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotechnica
    back: ClothingBackpackBiotechnica
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: BiotechnicaTechPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
