using Content.Shared._NC.CitiNet.Delivery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.CitiNet.UI.Delivery;

[GenerateTypedNameReferences]
public sealed partial class OTPKeypadWindow : DefaultWindow
{
    public event Action<string>? OnSubmit;

    public OTPKeypadWindow()
    {
        RobustXamlLoader.Load(this);
        
        Button0.OnPressed += _ => AddDigit("0");
        Button1.OnPressed += _ => AddDigit("1");
        Button2.OnPressed += _ => AddDigit("2");
        Button3.OnPressed += _ => AddDigit("3");
        Button4.OnPressed += _ => AddDigit("4");
        Button5.OnPressed += _ => AddDigit("5");
        Button6.OnPressed += _ => AddDigit("6");
        Button7.OnPressed += _ => AddDigit("7");
        Button8.OnPressed += _ => AddDigit("8");
        Button9.OnPressed += _ => AddDigit("9");
        
        ClearButton.OnPressed += _ => PinInput.Text = "";
        SubmitButton.OnPressed += _ => OnSubmit?.Invoke(PinInput.Text);
    }

    private void AddDigit(string digit)
    {
        if (PinInput.Text.Length < 4)
            PinInput.Text += digit;
    }
}
