using System;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Housing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._NC.Housing;

/// <summary>
/// Окно терминала недвижимости.
/// Отображает списки квартир и дизайнов, позволяет покупать и продавать.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ApartmentTerminalWindow : FancyWindow
{
    // === UI элементы ===
    private readonly Label _balanceLabel;
    private readonly BoxContainer _apartmentList;
    private readonly BoxContainer _designList;
    private readonly Button _buyButton;
    private readonly Button _sellButton;

    // === Выбранные элементы ===
    private NetEntity? _selectedApartment;
    private string? _selectedDesignId;

    // === Список кнопок для подсветки выбора ===
    private Button? _selectedAptButton;
    private Button? _selectedDesignButton;

    // === События для BUI ===
    /// <summary>Нажата кнопка "Купить". (NetEntity маркера, ID дизайна).</summary>
    public event Action<NetEntity, string>? OnBuyPressed;

    /// <summary>Нажата кнопка "Продать". (NetEntity маркера).</summary>
    public event Action<NetEntity>? OnSellPressed;

    public ApartmentTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        // Находим контролы по именам из XAML
        _balanceLabel = FindControl<Label>("BalanceLabel");
        _apartmentList = FindControl<BoxContainer>("ApartmentList");
        _designList = FindControl<BoxContainer>("DesignList");
        _buyButton = FindControl<Button>("BuyButton");
        _sellButton = FindControl<Button>("SellButton");

        // Подписываемся на кнопки
        _buyButton.OnPressed += _ =>
        {
            if (_selectedApartment != null && _selectedDesignId != null)
                OnBuyPressed?.Invoke(_selectedApartment.Value, _selectedDesignId);
        };

        _sellButton.OnPressed += _ =>
        {
            if (_selectedApartment != null)
                OnSellPressed?.Invoke(_selectedApartment.Value);
        };
    }

    /// <summary>
    /// Обновляет полное состояние окна из серверного BUI state.
    /// </summary>
    public void UpdateState(ApartmentTerminalBuiState state)
    {
        // Обновляем баланс
        _balanceLabel.Text = $"{state.PlayerBalance}$";

        // Обновляем список квартир
        PopulateApartments(state);

        // Обновляем список дизайнов
        PopulateDesigns(state);

        // Обновляем состояние кнопок
        UpdateButtons(state);
    }

    /// <summary>
    /// Заполняет список квартир из BUI state.
    /// </summary>
    private void PopulateApartments(ApartmentTerminalBuiState state)
    {
        _apartmentList.RemoveAllChildren();

        foreach (var apt in state.Apartments)
        {
            // Формируем текст кнопки
            var statusText = apt.IsFree ? "[СВОБОДНА]" : apt.IsOwnedByPlayer ? "[ВАША]" : "[ЗАНЯТА]";
            var designText = apt.CurrentDesignId ?? "—";
            var label = $"{apt.DisplayName}  {apt.Size.X}x{apt.Size.Y}  x{apt.PriceMultiplier:0.#}  {statusText}";

            var btn = new Button
            {
                Text = label,
                TextAlign = Label.AlignMode.Left,
                HorizontalExpand = true,
                Disabled = !apt.IsFree && !apt.IsOwnedByPlayer,
                ClipText = true,
            };

            // Захватываем NetEntity для клика
            var netEntity = apt.MarkerNetEntity;
            var isFree = apt.IsFree;
            var isOwned = apt.IsOwnedByPlayer;

            btn.OnPressed += _ =>
            {
                // Сбрасываем подсветку предыдущей выбранной квартиры
                if (_selectedAptButton != null)
                    _selectedAptButton.Modulate = Robust.Shared.Maths.Color.White;

                _selectedApartment = netEntity;
                _selectedAptButton = btn;
                btn.Modulate = new Robust.Shared.Maths.Color(0.5f, 1.0f, 0.5f);

                // Обновляем доступность кнопок
                _buyButton.Disabled = !isFree || _selectedDesignId == null;
                _sellButton.Disabled = !isOwned;
            };

            // Подсвечиваем если уже выбрана
            if (_selectedApartment == netEntity)
            {
                btn.Modulate = new Robust.Shared.Maths.Color(0.5f, 1.0f, 0.5f);
                _selectedAptButton = btn;
            }

            _apartmentList.AddChild(btn);
        }
    }

    /// <summary>
    /// Заполняет список дизайнов из BUI state.
    /// </summary>
    private void PopulateDesigns(ApartmentTerminalBuiState state)
    {
        _designList.RemoveAllChildren();

        foreach (var design in state.Designs)
        {
            var label = $"{design.Name}  {design.RequiredSize.X}x{design.RequiredSize.Y}  {design.BasePrice}$";

            var btn = new Button
            {
                Text = label,
                TextAlign = Label.AlignMode.Left,
                HorizontalExpand = true,
                ClipText = true,
                ToolTip = design.Description,
            };

            var designId = design.DesignId;

            btn.OnPressed += _ =>
            {
                // Сбрасываем подсветку предыдущего выбранного дизайна
                if (_selectedDesignButton != null)
                    _selectedDesignButton.Modulate = Robust.Shared.Maths.Color.White;

                _selectedDesignId = designId;
                _selectedDesignButton = btn;
                btn.Modulate = new Robust.Shared.Maths.Color(0.4f, 0.8f, 1.0f);

                // Обновляем Buy кнопку
                if (_selectedApartment != null)
                {
                    // Проверяем: выбранная квартира свободна?
                    var apt = state.Apartments.FirstOrDefault(a => a.MarkerNetEntity == _selectedApartment);
                    _buyButton.Disabled = apt == null || !apt.IsFree;
                }
            };

            // Подсвечиваем если уже выбран
            if (_selectedDesignId == designId)
            {
                btn.Modulate = new Robust.Shared.Maths.Color(0.4f, 0.8f, 1.0f);
                _selectedDesignButton = btn;
            }

            _designList.AddChild(btn);
        }
    }

    /// <summary>
    /// Обновляет доступность кнопок Buy/Sell.
    /// </summary>
    private void UpdateButtons(ApartmentTerminalBuiState state)
    {
        // Если ничего не выбрано — всё заблокировано
        if (_selectedApartment == null)
        {
            _buyButton.Disabled = true;
            _sellButton.Disabled = true;
            return;
        }

        var selectedApt = state.Apartments.FirstOrDefault(a => a.MarkerNetEntity == _selectedApartment);
        if (selectedApt == null)
        {
            _buyButton.Disabled = true;
            _sellButton.Disabled = true;
            return;
        }

        // Buy: квартира свободна + выбран дизайн
        _buyButton.Disabled = !selectedApt.IsFree || _selectedDesignId == null;

        // Sell: квартира принадлежит игроку
        _sellButton.Disabled = !selectedApt.IsOwnedByPlayer;
    }
}
