- type: job
  id: NCBooster
  name: Бустер
  description: Один из сотен членов уличных банд. Твоя жизнь дешевле твоего хрома. РОЛЬ ДЛЯ НАКАЗАНИЯ, ИГРАТЬ НА СВОЙ СТРАХ И РИСК.
  playTimeTracker: JobNCBooster
  icon: "JobIconCivilCitizen"
  salary: 0
  startingGear: NCBoosterGear

- type: startingGear
  id: NCBoosterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
