- type: job
  id: EdgeRunnerSolo
  name: Эджраннер
  description: Стандартный наёмник. Ищите нанимателя. Исполняйте заказы защита, убийство, сбор информации, поиск, похищение и многое другое.
  playTimeTracker: JobEdgeRunnerSolo
  icon: "JobIconCivilEdgerunner"
  salary: 15
  access:
    - NC_General
    - EdgeRunner
  startingGear: EdgeRunnerSoloGear

- type: startingGear
  id: EdgeRunnerSoloGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsCombat
    id: EdgeRunnerPDA
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
