- type: job
  id: Fixer
  name: Фиксер
  description: Посредник между заказчиками и исполнителями. Торговец.
  playTimeTracker: JobFixer
  icon: "JobIconCivilFixer"
  salary: 30
  access:
    - NC_General
    - Fixer
  startingGear: FixerGear
  special:
  - !type:AddComponentSpecial
    components:
    - type: TraumaSubscriber
      tier: Silver

- type: startingGear
  id: FixerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetectiveGrey
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesColorBlack
    id: FixerPDA
    eyes: ClothingEyesGlassesSunglasses
