- type: job
  id: Reaper
  name: Риппер
  description: Частный врач, работает как в своей клинике так и в паре с наемниками
  playTimeTracker: JobReaper
  icon: "JobIconCivilRipper"
  salary: 40
  access:
    - NC_General
  startingGear: ReaperGear

- type: startingGear
  id: ReaperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    id: RipperPDA
