- type: job
  id: NCPDCommander
  name: Коммандер
  description: Заместитель шефа полиции. Относится к младшему командному составу.
  playTimeTracker: JobNCPDCommander
  weight: 90
  salary: 300
  icon: "JobIconNCPDCommander"
  startingGear: NCPDCommanderGear
  supervisors: Начальник департамента полиции
  access:
    - NCPD_Patrol
    - NCPD_Armory
    - NCPD_Detective
    - NCPD_Command
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false

- type: startingGear
  id: NCPDCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecBlue
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetBasic
    id: NCPDCommanderPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterArmorBasic
