- type: job
  id: NCPDSergeant
  name: Старший патрульный
  description: Опытный патрульный, который повидал многое на улицах Найт-Сити. Знает, как обращаться с бандитами и как не попасть в передрягу
  playTimeTracker: JobNCPDSergeant
  weight: 45
  salary: 600
  icon: "JobIconNCPDPolice"
  startingGear: NCPDSergeantGear
  supervisors: Лейтенант
  access:
    - NCPD_Patrol
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false
    - type: TraumaSubscriber
      tier: Silver

- type: startingGear
  id: NCPDSergeantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatWarden
    id: NCPDSergeantPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterCoatWarden
