- type: job
  id: NCPDWatchAgent
  name: Агент Дозора
  description: Нетраннер при НСПД
  playTimeTracker: JobNCPDWatchAgent
  weight: 50
  salary: 200
  icon: "JobIconNCPDPolice"
  startingGear: NCPDWatchAgentGear
  supervisors: Начальник департамента полиции
  access:
    - NCPD_Patrol
    - NCPD_Detective
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false


- type: startingGear
  id: NCPDWatchAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackCyberdeckFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatFedoraBrown
    eyes: ClothingEyesGlassesSecurityVisor
    id: NCPDWatchAgentPDA
    outerClothing: ClothingOuterCoatDetective


- type: entity
  parent: ClothingBackpackSatchelSecurity
  id: ClothingBackpackCyberdeckFilled
  name: Рюкзак с декой
  components:
  - type: StorageFill
    contents:
    - id: NCCyberdeck
    - id: NCProgramBlind
    - id: NCProgramDrop
    - id: NCProgramShock
