- type: job
  id: ZhirafaJanitor
  name: Уборщик
  description: job-description-zhirafa_janitor
  playTimeTracker: JobZhirafaJanitor
  salary: 80
  icon: "JobIconCivilCitizen"
  startingGear: ZhirafaJanitorGear
  access:
    - NC_General

- type: startingGear
  id: ZhirafaJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackSatchel
    shoes: ClothingShoesColorBlack
    id: CitizenPDA
