- type: job
  id: ZhirafaEngeneer
  name: Инженер
  description: job-description-zhirafa_engeneer
  playTimeTracker: JobZhirafaEngeneer
  salary: 180
  icon: "JobIconCivilRipper"
  access:
    - NC_General
  startingGear: ZhirafaEngeneerGear

- type: startingGear
  id: ZhirafaEngeneerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    id: CitizenPDA
