using Content.Shared._NC.CitiNet;
using Content.Shared._NC.CitiNet.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.CitiNet.UI;

[GenerateTypedNameReferences]
public sealed partial class NetBrowserWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public Action<string>? OnNavigate;

    public NetBrowserWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GoButton.OnPressed += _ => OnNavigate?.Invoke(AddressBar.Text);
        AddressBar.OnTextEntered += args => OnNavigate?.Invoke(args.Text);
    }

    public void UpdateState(NetBrowserUiState state)
    {
        if (AddressBar == null || SiteList == null)
        {
            Logger.ErrorS("citinet.browser", "NetBrowserWindow: AddressBar or SiteList is null in UpdateState!");
            return;
        }

        Logger.InfoS("citinet.browser", $"NetBrowserWindow: Updating state. URL: {state.CurrentUrl}, Sites: {state.AvailableSiteIds.Count}");

        AddressBar.Text = state.CurrentUrl;

        SiteList.RemoveAllChildren();

        foreach (var siteId in state.AvailableSiteIds)
        {
            if (!_prototypeManager.TryIndex<NetSitePrototype>(siteId, out var site))
            {
                Logger.WarningS("citinet.browser", $"NetBrowserWindow: Failed to index site prototype: {siteId}");
                continue;
            }

            Logger.DebugS("citinet.browser", $"NetBrowserWindow: Adding bookmark: {site.Name} ({site.URL})");

            var btn = new Button
            {
                Text = site.Name,
                HorizontalAlignment = HAlignment.Left,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2)
            };

            if (site.URL == state.CurrentUrl)
                btn.AddStyleClass("FontColorSelected");

            var url = site.URL;
            btn.OnPressed += _ => OnNavigate?.Invoke(url);
            SiteList.AddChild(btn);
        }
        
        Logger.InfoS("citinet.browser", $"NetBrowserWindow: Population complete. SiteList child count: {SiteList.ChildCount}");
    }
}
