using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.CitiNet.UI;

[GenerateTypedNameReferences]
public sealed partial class NetHomeSiteUI : BoxContainer
{
    public NetHomeSiteUI()
    {
        RobustXamlLoader.Load(this);
    }
}
