- type: job
  id: TraumaTeamCoroner
  name: Коронер Trauma Team
  description: Вскрывает трупы и помогает копам из NCPD понять, почему этот парень стал трупом. Ваше кредо, мертвые не болтают, но их потроха могут рассказать чертовски много
  playTimeTracker: JobTraumaTeamCoroner
  weight: 90
  salary: 280
  icon: "JobIconTraumaCoroner"
  startingGear: TraumaTeamCoronerGear
  supervisors: Главный врач Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Morgue
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: TraumaSubscriber
      tier: Silver

- type: startingGear
  id: TraumaTeamCoronerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalGreen
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    id: TraumaTeamCoronerPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLab
