- type: job
  id: TraumaTeamIntern
  name: Интерн Trauma Team
  description: Вы — начальное звено пищевой цепочки Травмы. Ваша работа — быть человеком на побегушках, подчиняться старшим, выносить утки, слушать жалобы пациентов на ресепшене и учиться, как быть хорошим корпоративным врачём. Подчиняйтесь.
  playTimeTracker: JobTraumaTeamIntern
  weight: 20
  salary: 370
  icon: "JobIconTraumaIntern"
  startingGear: TraumaTeamInternGear
  supervisors: Главный врач Trauma Team, Ваш наставник и прочие сотрудники Trauma Team
  access:
    - Trauma_Medical
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: TraumaSubscriber
      tier: Bronze

- type: startingGear
  id: TraumaTeamInternGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalBlue
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    id: TraumaTeamInternPDA
    belt: ClothingBeltMedicalFilled
