- type: job
  id: TraumaTeamOperative
  name: Оперативник Trauma Team
  description: Охраняет парамедика Trauma Team
  playTimeTracker: JobTraumaTeamOperative
  weight: 60
  salary: 400
  icon: "JobIconTraumaOperator"
  startingGear: TraumaTeamOperativeGear
  supervisors: Главный врач Trauma Team, Парамедик Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Hangar
    - Trauma_Morgue
    - NC_General

- type: startingGear
  id: TraumaTeamOperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalGreen
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombat
    id: TraumaTeamOperativePDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterHardsuitTraumaTeamOperative
