- type: job
  id: TraumaTeamPsych
  name: КиберПсихолог Trauma Team
  description: Лечит от киберпсихоза при помощи терапии
  playTimeTracker: JobTraumaTeamPsych
  weight: 80
  salary: 320
  icon: "JobIconTraumaPsiholog"
  startingGear: TraumaTeamPsychGear
  supervisors: Главный врач Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Morgue
    - NC_General

- type: startingGear
  id: TraumaTeamPsychGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    id: TraumaTeamPsychPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLab
