- type: job
  id: TraumaTeamTech
  name: Техник Trauma Team
  description: занимается починкой техники Trauma Team
  playTimeTracker: JobTraumaTeamTech
  weight: 40
  salary: 250
  icon: "JobIconTraumaTech"
  startingGear: TraumaTeamTechGear
  supervisors: Главный врач Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Morgue
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: TraumaTeam
      color: "#4bdc99"
      icon: /Textures/Interface/VerbIcons/trauma_team.png
      visibleInWorld: false

- type: startingGear
  id: TraumaTeamTechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJeansBrown
    back: ClothingBackpackDuffel
    shoes: ClothingShoesColorWhite
    id: TraumaTeamTechPDA
    belt: ClothingBeltUtilityFilled
