using Content.Client.UserInterface.Fragments;
using Content.Shared._NC.CitiNet;
using Content.Shared._NC.Forensics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.CitiNet.UI.Forensics;

[GenerateTypedNameReferences]
public sealed partial class NcpdForensicsSiteUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    
    public event Action<int, NcpdForensicsAlertAction>? OnAlertAction;

    public NcpdForensicsSiteUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NcpdForensicsConsoleBuiState state)
    {
        AlertList.RemoveAllChildren();
        Map.MapBeacons.Clear();

        for (int i = 0; i < state.Alerts.Count; i++)
        {
            var alert = state.Alerts[i];
            if (alert.Archived)
                continue;

            var index = i;
            var rowPanel = new PanelContainer { Margin = new Thickness(2), MinHeight = 80 };
            rowPanel.StyleClasses.Add("BorderedWindowPanel");
            
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(8) };
            
            var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            header.AddChild(new Label { Text = alert.Victim.ToUpper(), FontColorOverride = Color.Yellow, HorizontalExpand = true, StyleClasses = { "LabelHeading" } });
            
            var actions = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };
            var archiveBtn = new Button { Text = Loc.GetString("nc-forensics-console-btn-archive"), MinWidth = 80 };
            var printBtn = new Button { Text = Loc.GetString("nc-forensics-console-btn-print"), MinWidth = 80, Modulate = Color.FromHex("#4DD0E1") };

            archiveBtn.OnPressed += _ => OnAlertAction?.Invoke(index, NcpdForensicsAlertAction.Archive);
            printBtn.OnPressed += _ => OnAlertAction?.Invoke(index, NcpdForensicsAlertAction.PrintTicket);

            actions.AddChild(archiveBtn);
            actions.AddChild(printBtn);
            header.AddChild(actions);

            row.AddChild(header);
            row.AddChild(new Label { Text = Loc.GetString("nc-forensics-console-location", ("loc", alert.Location)), FontColorOverride = Color.FromHex("#4DD0E1") });
            row.AddChild(new Label { Text = Loc.GetString("nc-forensics-console-time", ("time", alert.Time.ToString(@"hh\:mm\:ss"))), FontColorOverride = Color.LightSkyBlue });
            
            rowPanel.AddChild(row);
            AlertList.AddChild(rowPanel);

            // Add to Map
            if (alert.Coordinates != null)
            {
                var coords = _entManager.GetCoordinates(alert.Coordinates.Value);
                if (coords.EntityId.Valid)
                {
                    // Update map to use the correct grid/map
                    if (Map.MapUid == null)
                    {
                        Map.MapUid = coords.EntityId;
                        Map.MapRange = 500f; // Show large area by default
                        Map.ForceNavMapUpdate();
                    }

                    Map.MapBeacons.Add(new CitiNetMapBeaconData(
                        netEnt: NetEntity.Invalid,
                        label: alert.Victim,
                        icon: null,
                        color: Color.Red,
                        localPosition: coords.Position,
                        fontSize: 10
                    ) { IsDead = true });
                }
            }
        }
    }
}

public sealed partial class NcpdForensicsUIFragment : UIFragment
{
    private NcpdForensicsSiteUiFragment? _control;

    public override Control GetUIFragmentRoot() => _control!;

    public override void Setup(BoundUserInterface userInterface, EntityUid? fragmentOwner)
    {
        _control = new NcpdForensicsSiteUiFragment();
        _control.OnAlertAction += (index, action) => userInterface.SendMessage(new NcpdForensicsAlertActionMessage(index, action));
    }

    public override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is NcpdForensicsConsoleBuiState forensicsState)
            _control?.UpdateState(forensicsState);
    }
}
