- type: job
  id: MaxTacEraser
  name: Оперативник Max-Tac
  description: Стандартизированная ячейка ПсихОтряда и ваша персональная путевка в чистилище. Используя штатное снаряжение MAX-TAC, вы методично зачищаете последствия чужого цифрового безумия. Вы — последняя линия обороны, за которой только тишина и отчеты о летальных исходах
  playTimeTracker: JobMaxTacEraser
  weight: 60
  salary: 350
  icon: "JobIconMaxTacOperator"
  startingGear: MaxTacEraserGear
  supervisors: Штурм командир
  access:
    - MaxTac_General
    - MaxTac_Armory
    - NCPD_Patrol
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false
    - type: TraumaSubscriber
      tier: Silver
  - !type:AddCyberwareSpecial
    loseHum: false
    cyberware:
    - CyberwareExternalReactiveSublayer
    - CyberwareNeuroKerenzikovMaxTac
    - CyberwareNeuroTacticalSpartan
    - CyberwareNeuroSandevistanMaxTac

- type: startingGear
  id: MaxTacEraserGear
  equipment:
    jumpsuit: ClothingUniformNSPDNormisBlack
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetHardsuitSecurity
    id: MaxTacEraserPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterHardsuitMilitech
